#!/usr/bin/env bash
# ─── Set Random Wallpaper ───
# Picks a random image from ~/Pictures/walls and writes a hyprpaper.conf
# with the wallpaper {} block, then reloads hyprpaper.
#
# Usage: ./set-wall.sh [wallpaper_dir]

set -euo pipefail

WALL_DIR="${1:-$HOME/Pictures/walls}"
HYPRPAPER_CONF="$HOME/Desktop/dotfiles/hypr/hyprpaper.conf"

# Find all images (skip hidden files and .txt sidecars)
mapfile -t images < <(find "$WALL_DIR" -maxdepth 1 -type f \( \
    -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \
    -o -iname '*.webp' -o -iname '*.bmp' -o -iname '*.jxl' \
\) 2>/dev/null | sort)

if [[ ${#images[@]} -eq 0 ]]; then
    echo "No wallpapers found in $WALL_DIR"
    exit 1
fi

# Pick a random image
wall="${images[$((RANDOM % ${#images[@]}))]}"
echo "Setting wallpaper: $(basename "$wall")"

# Write hyprpaper.conf with wallpaper {} block
cat > "$HYPRPAPER_CONF" << EOF
# ─── Hyprpaper Config ───
# Auto-generated by scripts/set-wall.sh

splash = false

wallpaper {
    monitor =
    path = $wall
    fit_mode = cover
}
EOF

# Reload hyprpaper by killing and restarting it
killall -q hyprpaper || true
sleep 0.3
hyprpaper &
disown

echo "Done!"
